steps:
  # Build all supported versions.
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "version=1.0"
      - "--tag=gcr.io/$PROJECT_ID/docker-compose:latest"
      - "--tag=gcr.io/$PROJECT_ID/docker-compose:1.0"
      - "."
    id: "1.0"

  - name: "gcr.io/$PROJECT_ID/docker-compose"
    args: ["version"]

images:
  - "gcr.io/$PROJECT_ID/docker-compose:latest"
  - "gcr.io/$PROJECT_ID/docker-compose:1.0"
